services:
  mem0_store:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/mem0/storage
  openmemory-mcp:
    image: mem0/openmemory-mcp
    build: api/
    environment:
      - USER=${USER:-default_user}
      - API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=sqlite:////data/openmemory.db
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
      - ENV=production
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    volumes:
      - openmemory_data:/data
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8765"]
  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_ID=${NEXT_PUBLIC_USER_ID}

volumes:
  mem0_storage:
  openmemory_data:
